config/routes.rb
Rails.application.routes.draw do
  resources :destinations
  root 'welcome#index'

  get 'about' => 'welcome#about'
  get 'contact' => 'welcome#contact'

end

app/models/destination.rb
class Destination < ActiveRecord::Base
  has_attached_file :avatar, :styles => { :medium => "300x300>", :thumb => "100x100>" }, :default_url => "/images/:style/missing.png"
  validates_attachment_content_type :avatar, :content_type => /\Aimage\/.*\Z/
end

app/controllers/application_controller.rb
class ApplicationController < ActionController::Base
  # Prevent CSRF attacks by raising an exception.
  # For APIs, you may want to use :null_session instead.
  protect_from_forgery with: :exception
end

app/controllers/destinations_controller.rb
class DestinationsController < ApplicationController
  before_action :set_destination, only: [:show, :edit, :update, :destroy]
  geocoded_by :address
  after_validation :geocode
  
  # GET /destinations
  # GET /destinations.json
  def index
    # @destinations = Destination.all
    if params[:country] == nil
      @destinations = Destination.all
    else
      @destinations = Destination.where(country: params[:country].titleize)
    end
    @my_countries = Destination.select(:country).order(:country).distinct
  end

  # GET /destinations/1
  # GET /destinations/1.json
  def show
  end

  # GET /destinations/new
  def new
    @destination = Destination.new
  end

  # GET /destinations/1/edit
  def edit
  end

  # POST /destinations
  # POST /destinations.json
  def create
    @destination = Destination.new(destination_params)

    respond_to do |format|
      if @destination.save
        format.html { redirect_to @destination, notice: 'Destination was successfully created.' }
        format.json { render :show, status: :created, location: @destination }
      else
        format.html { render :new }
        format.json { render json: @destination.errors, status: :unprocessable_entity }
      end
    end
  end

  # PATCH/PUT /destinations/1
  # PATCH/PUT /destinations/1.json
  def update
    respond_to do |format|
      if @destination.update(destination_params)
        format.html { redirect_to @destination, notice: 'Destination was successfully updated.' }
        format.json { render :show, status: :ok, location: @destination }
      else
        format.html { render :edit }
        format.json { render json: @destination.errors, status: :unprocessable_entity }
      end
    end
  end

  # DELETE /destinations/1
  # DELETE /destinations/1.json
  def destroy
    @destination.destroy
    respond_to do |format|
      format.html { redirect_to destinations_url, notice: 'Destination was successfully destroyed.' }
      format.json { head :no_content }
    end
  end

  private
    # Use callbacks to share common setup or constraints between actions.
    def set_destination
      @destination = Destination.find(params[:id])
    end

    # Never trust parameters from the scary internet, only allow the white list through.
    def destination_params
      params.require(:destination).permit(:city, :country, :description, :population, :avatar, :latitude, :longitude, :address)
    end
end

app/controllers/welcome_controller.rb
class WelcomeController < ApplicationController
  def index
    @homeland = 'Long Island'
    @countries = %w[Ireland New\ Zealand France Cape\ Town]
    @images = %w[ireland.jpg new_zealand.jpg paris.jpg cape_town.jpg]

  end

  def about
    @color = params[:color]
    @size = params[:size].to_i
  end

  def contact
  end
end

app/helpers/application_helper.rb
module ApplicationHelper
  def active?(page)
    if current_page?(page)
      'active'
    end
  end
end

app/helpers/destinations_helper.rb
module DestinationsHelper
end

app/helpers/welcome_helper.rb
module WelcomeHelper
end

app/views/destinations/_form.html.erb
<%= form_for(@destination) do |f| %>
  <% if @destination.errors.any? %>
    <div id="error_explanation">
      <h2><%= pluralize(@destination.errors.count, "error") %> prohibited this destination from being saved:</h2>

      <ul>
      <% @destination.errors.full_messages.each do |message| %>
        <li><%= message %></li>
      <% end %>
      </ul>
    </div>
  <% end %>

  <div class="form-group">  <!-- deleted class="field" because we commented out that portion of scaffold.scss -->
    <%= f.label :city %><br>
    <%= f.text_field :city, class: "form-control", placeholder: "Enter a city"%>
  </div>
  <div class="form-group">
    <%= f.label :country %><br>
    <%= f.text_field :country, class: "form-control", placeholder: "Enter a country" %>
  </div>
  <div class="form-group">
    <%= f.label :description %><br>
    <%= f.text_area :description, class: "form-control", placeholder: "Enter a description" %>
  </div>
  <div class="form-group">
    <%= f.label :population %>
    <%= f.number_field :population, class: "form-control" %>
  </div>
  <div class="field form-group">
    <%= f.label :address %><br>
    <%= f.text_field :address, class: "form-control" %>
  </div>
  <div class="field form-group">
    <%= f.label :latitude %><br>
    <%= f.text_field :latitude, class: "form-control" %>
  </div>
   <div class="field form-group">
    <%= f.label :longitude %><br>
    <%= f.text_field :longitude, class: "form-control" %>
  </div>
  <div class="form-group">
    <%= f.label "Country Picture" %>
    <%= f.file_field :avatar %>
  </div>
  <div class="actions form-group">
    <%= f.submit class: "btn btn-primary"%>
  </div>
<% end %>

app/views/destinations/edit.html.erb
<h1>Editing Destination</h1>

<%= render 'form' %>

<%= link_to 'Show', @destination %> |
<%= link_to 'Back', destinations_path %>

app/views/destinations/index.html.erb
<p id="notice"><%= notice %></p>

<h1>My Destination Wish List</h1>

<!-- here is one way...more manual -->
<!-- <ul class="nav nav-pills" role="tablist">
  <li><%= link_to "All",destinations_path %></li>
  <li><%= link_to "France",destinations_path(country:"france") %></li>
  <li><%= link_to "Italy",destinations_path(country:"italy") %></li>
  <li><%= link_to "South Africa",destinations_path(country:"south africa") %></li>
</ul> -->

<!-- but here is a better way...a lot more efficient -->
<ul class="nav nav-pills" role="tablist">
  <li><%= link_to "All",destinations_path %></li>
  <% @my_countries.each do |c| %>
  <li> <%= link_to c.country, destinations_path(country: c.country) %> </li>
  <% end %>
</ul>

<div class="row">
    <% @destinations.each do |destination| %>
      <div class="col-md-4">
       <div class="panel panel-default">
        <div class="panel-body">
         <h2><%= destination.city %></h2>
         <%= image_tag destination.avatar.url(:thumb) %>
         <p>Population: <%= destination.population %></p>
         <h3><%= destination.country %></h3>
         <p><%= destination.description %></p>

         <div class="btn-group">
          <%= link_to 'Show', destination, class: "btn btn-default" %>
          <%= link_to 'Edit', edit_destination_path(destination), class: "btn btn-default" %>
          <%= link_to 'Destroy', destination, method: :delete, data: { confirm: 'Are you sure?' }, class: "btn btn-default" %>
         </div>
        </div>
      </div>
    </div>
  <% end %>
</div>


<br>

<%= link_to 'New Destination', new_destination_path %>

app/views/destinations/new.html.erb
<h1>New Destination</h1>

<%= render 'form' %>

<%= link_to 'Back', destinations_path %>

app/views/destinations/show.html.erb
<p id="notice"><%= notice %></p>

<h1><%= @destination.city %>, <%= @destination.country %></h1>
<p><strong>Population </strong><%= @destination.population %></p>

<h1><%= @destination.address %></h1>

<p><%= @destination.latitude %>, <%= @destination.longitude %></p>

<p><%= @destination.description %></p>

<%= image_tag @destination.avatar.url(:medium) %>

<p><strong>Description </strong> <%= @destination.description %> </p>

<div id="destination-map"></div>

<div class = "btn-group">

  <%= link_to 'Edit', edit_destination_path(@destination),class:"btn btn-default" %>
  <%= link_to 'Back', destinations_path,class:"btn btn-default" %>
</div>

<%= javascript_tag do %>
   latitude = '<%= j @destination.latitude.to_s %>';
   longitude = '<%= j @destination.longitude.to_s %>';
   address = '<%= j @destination.address %>';
   description = '<%= j @destination.description %>';
<% end %>

app/views/layouts/application.html.erb
<!DOCTYPE html>
<html>
<head>
  <title>Travelapp</title>

  <%= stylesheet_link_tag "https://maxcdn.bootstrapcdn.com/bootstrap/3.3.0/css/bootstrap.min.css" %>
  <%= stylesheet_link_tag "https://fonts.googleapis.com/css?family=Lobster+Two" %>
  <%= stylesheet_link_tag    'application', media: 'all', 'data-turbolinks-track' => true %>
  <%= javascript_include_tag 'application', 'data-turbolinks-track' => true %>
  <%= javascript_include_tag "https://maxcdn.bootstrapcdn.com/bootstrap/3.3.0/js/bootstrap.min.js" %>
  <%= javascript_include_tag "https://maps.googleapis.com/maps/api/js?key=<%= ENV['google_api_key'] %>" %>
  <%= csrf_meta_tags %>
</head>
<body>
  <nav class="navbar navbar-default">
    <div class="container-fluid">
      <!-- Brand and toggle get grouped for better mobile display -->
      <div class="navbar-header">
        <button type="button" class="navbar-toggle collapsed" data-toggle="collapse" data-target="#bs-example-navbar-collapse-1" aria-expanded="false">
          <span class="sr-only">Toggle navigation</span>
          <span class="icon-bar"></span>
          <span class="icon-bar"></span>
          <span class="icon-bar"></span>
        </button>
        <!-- <a class="navbar-brand" href= "/">Brand</a> -->
        <%= link_to "Travel", root_path, class:"navbar-brand" %>
      </div>

      <!-- Collect the nav links, forms, and other content for toggling -->
      <div class="collapse navbar-collapse" id="bs-example-navbar-collapse-1">
        <ul class="nav navbar-nav">
          <li class="<%= active?(about_path) %>"> <%= link_to "About", about_path(color:"yellow")%> </li>
          <li class="<%= active?(contact_path) %>"> <%= link_to "Contact", contact_path %> </li>
          <li class="<%= active?(destinations_path) %>"> <%= link_to "Destinations", destinations_path %> </li>
        </ul>
      </div><!-- /.navbar-collapse -->
    </div><!-- /.container-fluid -->
  </nav>
  <div class = "container">
    <!-- <%= link_to "Home",root_path %>
    <%= link_to "About",about_path %> -->
    <%= yield %>
  </div>



</body>
</html>

app/views/welcome/about.html.erb
<style>
  body {
    background: <%= @color %>;
  }
</style>


<h1>About Me</h1>
<p>Lots of interesting stuff</p>
<!--
<%= link_to "Not Blue", about_path, class: "btn btn-primary" %>
<%= link_to "Blue", about_path(color: "blue"), class: "btn btn-primary" %> -->

<p>My favorite color is <%= @color %></p>
<p>My shoe size is <%= @size %>.</p>
<% if @size >= 12 %>
  <p>Yeah, I have huge feet...</p>
<% end %>


<%= link_to "Blue", about_path(color: "blue"), class: "btn btn-primary" %>
<%= link_to "Red", about_path(color: "red"), class: "btn btn-danger" %>
<%= link_to "Green", about_path(color: "green"), class: "btn btn-success" %>
<%= link_to "Yellow", about_path(color: "yellow"), class: "btn btn-warning" %>

app/views/welcome/contact.html.erb
<h1>Contact Me</h1>
<p>
  Drop a line!
</p>

app/views/welcome/index.html.erb
<h1>Welcome to my Travel Site</h1>
<p>This is my very first trip away from <%= @homeland %>!</p>
<p>But I really want to visit ...</p>
<ul>
  <% @countries.each do |country| %>
    <li><%= country %></li>
  <% end %>
</ul>

<% @images.each do |pic| %>
  <%= image_tag pic, class:"img-responsive" %>
<% end %>

<div id="map-canvas">
  
</div>